### ISSUE TITLE
Fields that are NOT migrated in current migration script

### ISSUE THREAD

**Issue by simonrolph** [Spandex-at-Exeter/demography_database#10]
Fields to migrate from compadre, (probably via flat csv)
- [ ] study reason
- [ ] email
- [ ] contacted
- [ ] growth form rankier
- [ ] within site replication
- [ ] other matrices
- [ ] vectors

**Comment by sargentfrancesca** [comment]
so these are new fields present within the new compadre to be added to the database?

**Comment by DannyLBuss** [comment]
@simonrolph think we should skype about this, think we have two issues open for the same thing...... just so we are all on the same wavelength
