### ISSUE TITLE
Notes_about_contacting_author -> publication_contact_author_notes

### ISSUE THREAD

**Issue by simonrolph** [Spandex-at-Exeter/demography_database#103]
The species descriptor had 4 fields for this:

Notes_about_contacting_author (previously contacted)
Contacted.again
ContentEmail
Reply

@DannyLBuss suggests creating a single string field that concatenates these for archival referencing and to avoid nasty migration work

no decisions has been made yet

**Comment by DannyLBuss** [comment]
I have concatenated all the notes from these columns into a single string column called publication_contact_author_notes, this will be a new field. We don't need the other 4 fields above. 

publication_contact_author_notes - string field, needs adding to the publication model and can have a character limit of 2000 (authors responses etc. are inc. in this string

**Comment by simonrolph** [comment]
I will add this to db model and migration tonight if it isn't done by the end of the day

**Comment by sargentfrancesca** [comment]
Does this make the AuthorContact table redundant?

**Comment by DannyLBuss** [comment]
@sargentfrancesca and I have discussed the above and decided to keep all the fields separate. This means in the current author_contact table, some new fields need to be added and some field names need changing.

Existing fields 
- id
- publication_id
- date_contacted (publication_date_author_contacted) - date
- contacting_user_id 
- content_email_id (publication_correspondence_email_content) -> string not meta
- author_reply (publication_correspondence_author_reply) - string

New fields 
- publication_date_author_contacted_again - date
- publication_missing_data_id (FYI missing_data_metatable)
- publication_corresponding_author - string
- publication_corresponding_author_email - string

**Comment by simonrolph** [comment]
are `publication_corresponding_author` and `publication_corresponding_author_email` going to remain in the publication model as well? Or moved?

**Comment by sargentfrancesca** [comment]
Moved to the AuthorContact model

**Comment by DannyLBuss** [comment]
Is there any benefit of having them in both (sorry database newbie here)?

**Comment by simonrolph** [comment]
@DannyLBuss no

ok cool @sargentfrancesca
