### ISSUE TITLE
Remove matrix_checked from model 

### ISSUE THREAD

**Issue by DannyLBuss** [Spandex-at-Exeter/demography_database#106]
Hi both,
I didn't include matrix_checked in comadre as it is redundant. We have two columns: matrix_checked_count(numeric) and matrix_complete (boolean), therefore, the matrix_checked (t/f) column is not needed, as we will be counting how many times it has been checked and whether it is complete yet or not will be flagged. 
Hope that makes sense
D

**Comment by simonrolph** [comment]
matrix_checked is incorporated into the versioning model, I am leaving versioning in the hands of @sargentfrancesca 

matrix_complete is already in the database structure (in the matrix model)

matrix_checked_count is incorporated into the versioning model

**Comment by sargentfrancesca** [comment]
there is no matrix_checked in the models currently - I am assuming this has been removed already.
