### ISSUE TITLE
add Phil Wilson as a user to test the migration etc. 

### ISSUE THREAD

**Issue by DannyLBuss** [Spandex-at-Exeter/demography_database#115]
{
	"User": {
          "User": {
            "email" : "pw355@exeter.ac.uk",
            "username" : "phil_wilson",
            "role_id" : 2,
            "password" : "password",
            "confirmed" : 1, 
            "institute_id" : 2, 
            "institute_confirmed" : 1
            },

Q. what should the role_id be for the different users? 
Q. how do we hash a password? will phil be able to change his password?

**Comment by sargentfrancesca** [comment]
The role ID can be found by looking in phpmyadmin in the 'roles' table:
* 1 - Administrator
* 2 - Researcher
* 3 - Compadrino
* 4 - Moderator
* 5 - User
* 6 - Committee
* 7 - Developer

**Comment by sargentfrancesca** [comment]
Passwords are hashed in the migration method and must be changed by the user, they'll be able to do that on the front end profile edit, which comes with this framework
`u.password = generate_password_hash(us['password'])`
