### ISSUE TITLE
match up the users from publication_student in the csv and the compadrinos in users.json name : "Phil"

### ISSUE THREAD

**Issue by DannyLBuss** [Spandex-at-Exeter/demography_database#116]
Have finished putting all the users in users.json.

**Comment by Spandex-CDO** [comment]
@sargentfrancesca - hey lovely, any chance you can point me in the right direction on this. For info - we have added the compadrinos as users in the json file. They can log-in using their emails. There is a field in the database called publication_student which assigns students to publications. However, I'm not sure how to link between the publication_student column and the users in the json. Ideally it would be cool to have a way to filter the publication_user field so if say d.l.buss@exeter.ac.uk logs in, on my compadrino home page all the publications I am assigned to will appear. I think I can manage this, except building the direct link between the log-in emails and the publication_student field is unclear to me. Thank you muchly

**Comment by sargentfrancesca** [comment]
This was a temporary string field for reference.  Before we left, we agreed that each publication's version's user_id would be that of the compadrino responsible for it - so in the initial migration, each Publication would be assigned to the user in that way. @simonrolph could assist in this - migrate users first, then query for a User with the matching name/email address, and return their ID. There are no foreign keys linking the string field to the User model.

You can find this in `manage.py`

Pseudo code could be

    #Publication Migration
    ...
    publication.publication_student = dict['publication_user'] #Say, 'Phil'
    ...

    #Publication Version
    ...
    publication_user = User.query.filter_by(name=publication.publication_student).first()
    version.user_id = publication_user.id
    ...

**Comment by Spandex-CDO** [comment]
@sargentfrancesca why would we not want to link User to Publication?
