### ISSUE TITLE
Add fields for seed bank, clonality and vectors (proportions and abundance sep) in species/population db model

### ISSUE THREAD

**Issue by simonrolph** [Spandex-at-Exeter/demography_database#138]
Seedbank - boolean
Clonality - ramet or genet

**Comment by Spandex-CDO** [comment]
@simonrolph @robcito are these fields - 
i) whether the Species should normally have a seedbank True or FALSE (species model)?
ii) whether the population being studied, studied the Ramets or the Genets (population model)?

**Comment by RobSalGo** [comment]
both should be MPM attributes
rob s-g


New book on the Evolution of Senescence in the Tree of Life http://tinyurl.com/SenescenceBook

"Aliud iter ad prosperitatem nos est: id est omnibus rebus vincere"
.:.:.:.:.:.:.:.:.:.:.:.:.:.:.:.:.:.:.:.:.:.:.:.:.:.:.:.
Dr Rob Salguero-Gómez
NERC Independent Research Fellow at the University of Sheffield
Honorary research fellow of the University of Queensland
Guest researcher of the Max Planck Institute for Demographic Research
https://www.sheffield.ac.uk/aps/staff-and-students/acadstaff/salguero-gomez
http://sites.google.com/site/RobResearchSite/


On 20 Feb 2017, at 20:57, CDO-at-Exeter <notifications@github.com<mailto:notifications@github.com>> wrote:


@simonrolph<https://github.com/simonrolph> @robcito<https://github.com/robcito> are these fields -
i) whether the Species should normally have a seedbank True or FALSE (species model)?
ii) whether the population being studied, studied the Ramets or the Genets (population model)?

**Comment by Spandex-CDO** [comment]
@robcito I just need to clarify this one more time pretty please! Please circle a or b as appropriate 

The seedbank column (TRUE/FALSE) is:
a) whether the individual matrix currently contains a seedbank class?
or 
b) whether the species they studied is known to have a seedbank in 'real-life'?

The clonality column (TRUE/FALSE) is:
a) whether the individual matrix contains clonality?
or
b) whether the species they studied here is known to be clonal?

Thank you

Danny

**Comment by RobSalGo** [comment]
@robcito<https://github.com/robcito> I just need to clarify this one more time pretty please! Please circle a or b as appropriate

The seedbank column (TRUE/FALSE) is:
a) whether the individual matrix currently contains a seedbank class? FALSE
or
b) whether the species they studied is known to have a seedbank in 'real-life’? TRUE

The clonality column (TRUE/FALSE) is:
a) whether the individual matrix contains clonality? FALSE
or
b) whether the species they studied here is known to be clonal? TRUE

Thank you

Danny

**Comment by DannyLBuss** [comment]
Amazing! Thanks Rob
