### ISSUE TITLE
Dirty Commit Issue

### ISSUE THREAD

**Issue by DannyLBuss** [Spandex-at-Exeter/demography_database#144]
Hi All,

Francesca has been helping me sort some commit issues out in the database. To avoid future dirty commits, it is recommended that you delete your demography_database repository completely and then download a new one. 

@Spandex-at-Exeter/compadre-and-comadre-databases 

Thank you, all the best 

Danny

**Comment by jonesor** [comment]
Hi Danny, 
Just to clarify -- Dirty Commits are caused when you don't sync properly before working, and end up with version conflicts. Is that correct?

Cheers,
Owen

**Comment by Spandex-CDO** [comment]
Hi Owen 

Yes, we had some confidential user information such as passwords in some of the old code that have now been deleted from all old commits etc. A clean slate will prevent future problems and dirty commits.

All the best,
Danny
