### ISSUE TITLE
missing protocol entries

### ISSUE THREAD

**Issue by simonrolph** [Spandex-at-Exeter/demography_database#167]
or at least I can't find it

**Comment by simonrolph** [comment]
same for pub_title

**Comment by DannyLBuss** [comment]
Hi simon, source_type? What is the field? It doesn't seem to be in the data?
Publication title isn't in the data either, but I will add it to the protocol now, for future collection.

Cheers, D

**Comment by DannyLBuss** [comment]
I have added publication title. source_type doesn't seem to be in the data, so I haven't added this.
