### ISSUE TITLE
When doi is NA, publication is always Nyman

### ISSUE THREAD

**Issue by simonrolph** [Spandex-at-Exeter/demography_database#20]

**Comment by sargentfrancesca** [comment]
This is because Publications are grouped by DOI, and the final else statement sets everything to Nyman, right?

**Comment by simonrolph** [comment]
It occurs in migration in cases when DOI is NA so i assume so, I'm not too familiar with the migration script. Cases with no DOI; matrix source is not published in a paper such as in a talk or non-peer reviewed report etc
