### ISSUE TITLE
check columns in comadre are in compadre database 

### ISSUE THREAD

**Issue by simonrolph** [Spandex-at-Exeter/demography_database#27]

**Comment by sargentfrancesca** [comment]
I thought it was the other way around, as in compadre there are growth types etc? Main difference is the Studied Sex, which already has the meta table implemented ready for comadre

**Comment by simonrolph** [comment]
I hadn't actually checked, I raised this issue to make sure both compadre and comadre are compatable with regards to their columns, and we can migrate a flat csv with both animals and plants successfully.

**Comment by DannyLBuss** [comment]
I'll double check this

**Comment by DannyLBuss** [comment]
Have been through and will add additional columns in issue #52 . 

For info: Comadre does not have the following columns: 
1. GrowthType (soon to be organism type, for which we could add some generic categories, e.g. bird, fish (not for me to decide)
2. DicotMonoc (NA for Comadre)
3. AngioGymno (Na for Comadre)
4. Raunkier Growth Form (NA for Comadre) 
5. Authority (Taxonomic authority of SpeciesAccepted, as per The Plant List)
6. TaxonomicStatus (Taxonomic correspondence of SpeciesAuthor with SpeciesAccepted)
7. TPLVersion (Version of the Plant List used for taxonomic validation) 

For info: Compadre does not have the following columns that are in Comadre:
1. ColCheckOK (Whether the taxonomy detailed here has been verified at the Catalogue of Life)
2. ColCheckDate (Date it was checked at CoL)
3. SpeciesEpithetAccepted (Taxonomic species epithet name of study SpeciesAccepted, as per CoL)

For info: Comadre and Compadre have the same variables with different column headings for:
1. InfraspeciesAccepted (Compadre) -> Infraspecific (Comadre) 
2. Genus (Compadre) -> GenusAuthor (Comadre)
