### ISSUE TITLE
New columns in Plant Trait

### ISSUE THREAD

**Issue by sargentfrancesca** [Spandex-at-Exeter/demography_database#32]
New column in Plant Trait:
(meta table)
Dave's Growth Types

> > Tree
> > Shrub
> > Closed Perennial
> > Open Perennial
> > Monocarpic
> > Algae
> > NA

@simonrolph @DannyLBuss please could you provide a descriptive sentence for each? I can add these as a meta table.

**Comment by simonrolph** [comment]
Tree - Large woody plant with a trunk and supporting branches
Shrub - Small to medium-sized woody plant, distinguished from trees by shorter height and multiple stems 
Closed Perennial: Non-woody plants with multiple reproductive events in their lifetime and occurs primarily in shaded habitats such as forests.
Open Perennial: Non-woody plants with multiple reproductive events in their lifetime and occurs primarily in unshaded habitats such as grassland.
Monocarpic: Plants with a single reproductive event in their lifetime. This includes biennials.
Algae: Organisms with chlorophyll as their primary photosynthetic pigment and lack a sterile covering of cells around their reproductive cells
NA: Does not fit into growth type category
