### ISSUE TITLE
New columns in Population

### ISSUE THREAD

**Issue by sargentfrancesca** [Spandex-at-Exeter/demography_database#33]
New columns in Population:
(meta tables)
Invasive Status Study

> > Native
> > NA
> > Introduced
> > Invasive
> > Invasive Status Elsewhere
> > Invasive
> > Introduced
> > Not Introduced
> > NA

**Comment by simonrolph** [comment]
Invasive status study

Native: The species population is studied in its native distribution
NA: 
Introduced: The species population is studied outside of its native range
Invasive: The species is studied outside of its native range and is invasive

Invasive status elsewhere

Invasive: The species is classified as invasive on an invasives database
Introduced: The species is classified as introduced on an invasives database
Not introduced: The species is not classified as introduced or invasive on an invasives database
NA: There is not sufficient information as to whether the species is invasive or introduced
