### ISSUE TITLE
New columns in Fixed

### ISSUE THREAD

**Issue by sargentfrancesca** [Spandex-at-Exeter/demography_database#35]
New columns in Fixed:
Census Timing:

> > Pre
> > Post
> > Flow
> > NATS
> > NA
> > UTD

@simonrolph @DannyLBuss please could you provide a descriptive sentence for each? I can add these as a meta table.

**Comment by simonrolph** [comment]
Pre: Birth pulse; pre-reproductive census timing
Post: Birth pulse; post-reproductive census timing
Flow: Birth Flow; Non-periodic reproductive events that occur consistently throughout the year 
NATS: No access to source
NA: 
UTD: Unable to determine census timing from original source
