### ISSUE TITLE
UTD; NA; NATS; NDY

### ISSUE THREAD

**Issue by DannyLBuss** [Spandex-at-Exeter/demography_database#38]
Discussion: These variations of NAs are still upsetting my OCD in the database. I think we need to decide what option from below is the best one. 

Option 1: From an Analysis point of view all these fields still mean NA when doing comparative analysis. Therefore, should we revert all back to to NA, to avoid having multiple fields that may be unnecessary.  

Option 2: All these 4 fields appear as NAs to standard users, but when COMPADRINOS log in they can now be seen as described above (NA; UTD; NATS; NDY). In this instance an NA could still mean multiple things. A compadrino still might not be sure if it was an NA because the compadrino completing that record didn't have the expertise to find the information they needed or simply because the information was not available or in some cases it is simply not applicable to that entry, for example, it is an animal with NA for growth type. Maybe to overcome this we simply need clearer definitions of these fields or more fields/options for compadrinos to cover all these basis. 

Option 3: We leave it how it is, make sure our definitions for the fields we have are ship shape and let others figure it out for themselves when conducting analyses. 

@sargentfrancesca how difficult will it be to manage option 2? 

@simonrolph what are your views?

**Comment by sargentfrancesca** [comment]
W/ regards to option 2, I'm not sure yet. In the case of serving all to the front end as NA, and the export, it just needs to be a function or method. It just feels a little messy and hacky, and generally with these things, it makes better sense to have a clearer definition. So if 1 and 3 fail, we can do 2?

**Comment by sargentfrancesca** [comment]
Are we closer to deciding on this?

**Comment by DannyLBuss** [comment]
For the fields that we have completed, I am going to change all to NA. For the fields not yet complete, I am going to leave them as they are for now for clarity and once complete change all to NA (either through the CSV for now, or on the front-end once ready for Compadrinos to use)

**Comment by DannyLBuss** [comment]
For an update on this. Currently, those rows of data that have been released will only contain NA. Those rows of data from the descriptor file and unreleased (database_master_version-> "X") will contain NDY or NA or NATS 

NDY - Not done yet
NATS - Not able to source

**Comment by DannyLBuss** [comment]
I believe this has been resolved with out NDY and NA traffic light system? :)
