### ISSUE TITLE
schema.html

### ISSUE THREAD

**Issue by DannyLBuss** [Spandex-at-Exeter/demography_database#43]
To describe the structure and fieldnames of the database in an easy to understand format:

Columns within Species MetaTable:
SpeciesAccepted
SpeciesAuthor
CommonName

Columns within Traits (previous Plant Traits) MetaTable:
OrganismType
DicotMonoc
AngioGymno
GrowthType-> OrganismType
GrowthFormRaunkier 
GrowthType_Spand_Ex

Columns within Taxonomy MetaTable:
Genus
Family
Order
Class
Phylum
Kingdom

Fixed MetaTable Edits:
1. Remove Vector Availabilities 
2. Remove Stage Class info
3. Add boolean column named Vectors Available (Fields: True, False, NA)
4. Add string column name Vectors

Add Publication MetaTable Info? Columns include: Authors, Journal, YearPublished, DOI.ISBN, AdditionalSource, NumberPopulations

**Comment by simonrolph** [comment]
Can this be closed now we have all the schema spy stuff?

**Comment by sargentfrancesca** [comment]
Yep!
