### ISSUE TITLE
Make sure columns from CSV match with models.py

### ISSUE THREAD

**Issue by sargentfrancesca** [Spandex-at-Exeter/demography_database#47]
- Add outstanding columns as fields
- Remove stagnant fields

**Comment by sargentfrancesca** [comment]
Issue #44 needs to be completed before this can be resolved ( @simonrolph ) but I'll check the others now

**Comment by sargentfrancesca** [comment]
@DannyLBuss 'Growth Type Compadre' - what are the possible values for this? 

This is the Raunkier growth types Simon was talking about in issue #10 , do you still need me to list the possible values or have we already got them somewhere?

**Comment by DannyLBuss** [comment]
The gbif_key column is not needed - @sargentfrancesca would you like the gbif_id column to be titled gbif_key instead so it doesn't appear like a meta-table?

**Comment by sargentfrancesca** [comment]
that's a really good idea, as long as it works well with everything else and we're happy to call it GBIF key :)

**Comment by DannyLBuss** [comment]
@simonrolph do you think GBIF key is a good name? or, would you prefer GBIF_taxon_key?

**Comment by sargentfrancesca** [comment]
I don't think simon is working on this today, so I'm just going to go ahead and remove gbif_id and add gbif_taxon_key - it can be changed at a later date

**Comment by sargentfrancesca** [comment]
So, just to match the CSV headers with the field names in models.py @DannyLBuss
