### ISSUE TITLE
Add Version Info etc. from Compadre R Object into Flat CSV 

### ISSUE THREAD

**Issue by DannyLBuss** [Spandex-at-Exeter/demography_database#52]
Woopsee, missed off a few bits of info, will add this in when I get a min 
1. Version (soon to be called Origin_version)
2. DateCreated
3. NumberSpeciesAccepted
4. NumberStudies
5. NumberMatrices
6. Agreement
7. Authority
8. TaxonomicStatus
9. TPLVersion
10. ColCheckOK
11. ColCheckDate
12. SpeciesEpithetAccepted

Will update: column name, data type (ie boolean, meta table, integer, float, string), parent table (species, study) tomorrow and re-assign Chez.

**Comment by sargentfrancesca** [comment]
@DannyLBuss  
Things we already have in the database:
- TPL Version
- Taxonomic Status
- Species Ephitet Accepted
- Authority
1. So, the version is the version of the R-object released by the core committee? 
2. is DateCreated the same thing? Or is it the date it is entered by the compadrino?
3. ColCheckOK and ColCheckDate - this isn't the same as our statuses? Ie red green amber

**Comment by DannyLBuss** [comment]
TPL Version, Taxonomic Status and Authority are not in the most recent released of COMPADRE, Species Ephitet Accepted is only in COMADRE and not COMPADRE :)
