### ISSUE TITLE
Implement suitable date system to parse between R, CSV, Python and MySQL

### ISSUE THREAD

**Issue by sargentfrancesca** [Spandex-at-Exeter/demography_database#65]

**Comment by DannyLBuss** [comment]
Hi @sargentfrancesca 

Date layout for ColCheckDate - 08082016
Date layout for database date_created (version model) - Aug_12_2016 

Will check for any other hidden date columns now

D

**Comment by sargentfrancesca** [comment]
This is solved, right? 
Dates in R and the CSV appear as dd/mm/yyyy and are converted to mysql's yyyy-mm-dd like this:
`datetime.datetime.strptime(data['publication_date_digitization'], "%d/%m/%Y").strftime("%Y-%m-%d") if data['publication_date_digitization'] else None`
