### ISSUE TITLE
Amend migration to catch 'None' as well as 'NA'

### ISSUE THREAD

**Issue by sargentfrancesca** [Spandex-at-Exeter/demography_database#71]
Publications with the string value "None" for DOI_ISBN aren't being caught in the same way that "NA" or "" are, so they are being saved as a whole new Publication type

```
 for key, value in new_dict.iteritems():
        if value == "NA":
            new_dict[key] = None
        if value == "":
            new_dict[key] = None
```

**Comment by DannyLBuss** [comment]
Ok, please can you send me a new list of the populations once you have amended this :)
