### ISSUE TITLE
Include a boolean Independence Flag Column (Fixed_Independence_flag) to determine which Matrices to use for comparative analysis whilst avoiding Pseudoreplication 

### ISSUE THREAD

**Issue by DannyLBuss** [Spandex-at-Exeter/demography_database#74]

**Comment by sargentfrancesca** [comment]
Cool, do you have any proposed workflows? Will it be implemented in the CSV?

**Comment by DannyLBuss** [comment]
Only just seen this, sorry, Yes, I'll get the Compadrinos on it so it is in the CSV, please can it be in fixed so that only the exeter team can view it for now, ideally it would be great to implement some sort of versioning, but this isn't a priority so for now we'll stick with the boolean column called "fixed_independence_flag"

**Comment by DannyLBuss** [comment]
@sargentfrancesca did you add "fixed_independence_flag" as an embargo column? if so, it can be boolean - TRUE/FALSE

**Comment by DannyLBuss** [comment]
@sargentfrancesca can we do this tomorrow also, so you can show me how to differentiate between the embargo and non-embargo stuff  :)
