### ISSUE TITLE
Write python script that monitors IUCN and GISD status on websites and checks if database is still correct

### ISSUE THREAD

**Issue by DannyLBuss** [Spandex-at-Exeter/demography_database#79]
Hi Chez, I think this only needs to be done once a month maybe even less as the rate of change of the IUCN and ESA websites is very slow. 

Is it possible? :)

**Comment by sargentfrancesca** [comment]
Yesyes, can be done. Two stages...

1) When new species enters the database
2) As a monthly system task

**Comment by DannyLBuss** [comment]
👍  both please

**Comment by DannyLBuss** [comment]
I have not had time to do this and will be added to the list of potential upgrades for future database
