### ISSUE TITLE
Colour field

### ISSUE THREAD

**Issue by sargentfrancesca** [Spandex-at-Exeter/demography_database#85]
What is this/why do we have it?

**Comment by simonrolph** [comment]
touché!

Currently the colour of publications on the species overview page is generated via js to make a hex colour hash based of the internal id, ages ago i thought it would be easier to generate and store hex hashes in the db and just template it in that way but never finished it. Probably just delete the field for the moment and I'll work out something less hacky later as it's super low priority.

**Comment by simonrolph** [comment]
colour generated on migration
