### ISSUE TITLE
Add new field for geometries - boolean 

### ISSUE THREAD

**Issue by sargentfrancesca** [Spandex-at-Exeter/demography_database#92]
Exact coordinates

**Comment by simonrolph** [comment]
explanation:

The advantage of using lat + long as degrees, mins, seconds is that you get a measure of how accurate you are by whether a value has been given for seconds. When we converted to decimal, this is lost, so a boolean field (true, false) will be added to state whether the coordinates are exact (to the second) or not.

**Comment by simonrolph** [comment]
Chose to keep deg,min,sec columns instead
