### ISSUE TITLE
Add students to JSON file, add to version.user_id on migration script

### ISSUE THREAD

**Issue by simonrolph** [Spandex-at-Exeter/demography_database#97]
A string field

**Comment by sargentfrancesca** [comment]
@DannyLBuss is finding out the relevant information, will need to be added to users.json (extending the current admin user as an array) in this format:

```
{
            "email" : "unique email address",
            "username" : "we can derive this ourselves",
            "role_id" : 3,
            "password" : "assign an arbitrary word, it is hashed in the migrate function",
            "confirmed" : 1, 
            "institute_id" : X, 
            "institute_confirmed" : 1
            }
```

Where X represents the database table row ID for the institute they represent, must be represented as an integer

Also would be good to add users.json to the .gitignore and remove previous versions of it, and supply maybe a template in the Wiki.

**Comment by sargentfrancesca** [comment]
Mmmm represent, wordy
